### ISSUE TITLE
Can't create output model + plots (pytorch) 

### ISSUE THREAD

**Issue by alon7** [facebookresearch/dlrm#41]
Hi,

I'm running the benchmark (./bench/dlrm_s_criteo_kaggle.sh) with the smaller dataset 
I added to the command the `--save-model=./output/model.pt` and `--memory-map` flags
by using the memory map i was able to actually load the data, and I think the training was successful as I saw the following output:
```sh
Finished training it 297984/306969 of epoch 0, 41.97 ms/it, loss 0.449257, accuracy 79.112 %
Finished training it 299008/306969 of epoch 0, 41.55 ms/it, loss 0.446398, accuracy 79.331 %
Finished training it 300032/306969 of epoch 0, 42.07 ms/it, loss 0.448324, accuracy 79.166 %
Finished training it 301056/306969 of epoch 0, 41.56 ms/it, loss 0.447720, accuracy 79.162 %
Finished training it 302080/306969 of epoch 0, 41.75 ms/it, loss 0.443990, accuracy 79.356 %
Finished training it 303104/306969 of epoch 0, 41.58 ms/it, loss 0.445195, accuracy 79.299 %
Finished training it 304128/306969 of epoch 0, 41.76 ms/it, loss 0.448235, accuracy 79.118 %
Finished training it 305152/306969 of epoch 0, 41.64 ms/it, loss 0.447002, accuracy 79.177 %
Finished training it 306176/306969 of epoch 0, 41.81 ms/it, loss 0.446282, accuracy 79.279 %
Finished training it 306969/306969 of epoch 0, 41.33 ms/it, loss 0.445721, accuracy 79.342 %
```

A few points that I couldn't understand:
1. I see many filed that with `.npz` extension in my folder but I don't see the file name that is passed in the benchmark script `./input/kaggleAdDisplayChallenge_processed.npz`
2. save model doesn't save anything to the output folder 
3. How can I generate the plots from the benchmark?
4. What is the recommended hardware for training on the kaggle ad dataset? I'm using a machine with 64 cpu cores and it took about 5 hours

Any help will be greatly appreciated!

**Comment by mnaumovfb** [comment]
Let me answer your questions below:

1. If you use --memory-map the final pre-processed dataset is broken into multiple files (e.g. *_reordered.npz) rather than being packaged into a a single file (e.g. kaggleAdDisplayChallenge_processed.npz).  

2. Please add a testing frequency flag, which will determine when the model is saved. So your command line would be something like
> ./bench/dlrm_s_criteo_kaggle.sh "--test-freq=20000 --save-model=./output/model.pt --memory-map" 

3. What plots would you like to generate? If you are trying to reproduce the convergence plots on the webpage, you can preprocess the output log using Python or simply upload it into Excel spreadsheet and use "text to columns" function with data split by spaces.

4. We do not recommend a particular system. However, as a reference I wanted to mention that if we run on a system with a single GPU (V100), it typically takes around 1 hour for training (without testing) to finish with default parameters.

**Comment by mnaumovfb** [comment]
I'm assuming this is resolved. Closing.

**Comment by nzarif** [comment]
> 2. Please add a testing frequency flag, which will determine when the model is saved. So your command line would be something like
> 
> > ./bench/dlrm_s_criteo_kaggle.sh "--test-freq=20000 --save-model=./output/model.pt --memory-map"

When --test-freq is added to the command line it still won't save the model unless the accuracy has increased, yes? As a result, when running on random data the model will never be saved since accuracy is always zero?

--

**Comment by mnaumovfb** [comment]
Technically you are correct, the accuracy needs to increase above 0 at least once for the model to be saved. However, I would expect a model to correctly predict at least a few items even on random data (following a saying that even a broken clock is right twice a day). Nonetheless, if you really want to force the model to be written out you can always adjust the `if is_best:` statement [on line 1083 in dlrm_s_pytorch.py](https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L1083)

**Comment by nzarif** [comment]
Thank you so much for the quick response. What you say should technically happen but in practice, the accuracy remains always zero so no model is saved. My next question is then does it make sense to do inference using random data without a saved model? Just for profiling purposes.

**Comment by mnaumovfb** [comment]
If you run inference using the --inference-only flag, without providing the previously saved model, then the code will simply create the model with random values for its weights. I would say that if you are looking at system performance that should be fine. Perhaps a more important aspect that influences performance is the distribution of input indices, rather than the values of the weights.
